I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 183, in script
    call screen dungeon_command
  File "renpy/common/000statements.rpy", line 670, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "renpy/common/00action_other.rpy", line 585, in __call__
    rv = self.callable(*self.args, **self.kwargs)
  File "game/DungeonCrawl.rpy", line 940, in moveForwards
    update_coord(dx,dy)
  File "game/DungeonCrawl.rpy", line 259, in update_coord
    update_seen()
NameError: name 'update_seen' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 183, in script
    call screen dungeon_command
  File "E:\Ren Py\renpy-8.1.3-sdk\renpy\ast.py", line 2259, in execute
    self.call("execute")
  File "E:\Ren Py\renpy-8.1.3-sdk\renpy\ast.py", line 2241, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "E:\Ren Py\renpy-8.1.3-sdk\renpy\statements.py", line 342, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 670, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "E:\Ren Py\renpy-8.1.3-sdk\renpy\exports.py", line 3347, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "E:\Ren Py\renpy-8.1.3-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "E:\Ren Py\renpy-8.1.3-sdk\renpy\display\core.py", line 3582, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "E:\Ren Py\renpy-8.1.3-sdk\renpy\display\core.py", line 4543, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "E:\Ren Py\renpy-8.1.3-sdk\renpy\display\layout.py", line 1179, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "E:\Ren Py\renpy-8.1.3-sdk\renpy\display\layout.py", line 1179, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "E:\Ren Py\renpy-8.1.3-sdk\renpy\display\layout.py", line 1179, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "E:\Ren Py\renpy-8.1.3-sdk\renpy\display\screen.py", line 770, in event
    rv = self.child.event(ev, x, y, st)
  File "E:\Ren Py\renpy-8.1.3-sdk\renpy\display\layout.py", line 1179, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "E:\Ren Py\renpy-8.1.3-sdk\renpy\display\layout.py", line 1403, in event
    rv = super(Window, self).event(ev, x, y, st)
  File "E:\Ren Py\renpy-8.1.3-sdk\renpy\display\layout.py", line 281, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "E:\Ren Py\renpy-8.1.3-sdk\renpy\display\layout.py", line 1179, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "E:\Ren Py\renpy-8.1.3-sdk\renpy\display\behavior.py", line 528, in event
    rv = run(action)
  File "E:\Ren Py\renpy-8.1.3-sdk\renpy\display\behavior.py", line 379, in run
    return action(*args, **kwargs)
  File "renpy/common/00action_other.rpy", line 585, in __call__
    rv = self.callable(*self.args, **self.kwargs)
  File "game/DungeonCrawl.rpy", line 940, in moveForwards
    update_coord(dx,dy)
  File "game/DungeonCrawl.rpy", line 259, in update_coord
    update_seen()
NameError: name 'update_seen' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.3.23091805
Dungeons of Hundwick 0.13 Map Update
Mon Dec 18 21:51:58 2023
